// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: push.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 登录响应数据
type LoginGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerInfo    *PlayerInfo            `protobuf:"bytes,1,opt,name=player_info,json=playerInfo,proto3" json:"player_info,omitempty"` // 玩家信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginGameResponse) Reset() {
	*x = LoginGameResponse{}
	mi := &file_push_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginGameResponse) ProtoMessage() {}

func (x *LoginGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_push_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginGameResponse.ProtoReflect.Descriptor instead.
func (*LoginGameResponse) Descriptor() ([]byte, []int) {
	return file_push_proto_rawDescGZIP(), []int{0}
}

func (x *LoginGameResponse) GetPlayerInfo() *PlayerInfo {
	if x != nil {
		return x.PlayerInfo
	}
	return nil
}

// 玩家信息
type PlayerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`                                      // 用户ID
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`                             // 昵称
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`                                 // 头像
	Sex           int32                  `protobuf:"varint,4,opt,name=sex,proto3" json:"sex,omitempty"`                                      // 性别
	RegisterTime  string                 `protobuf:"bytes,5,opt,name=register_time,json=registerTime,proto3" json:"register_time,omitempty"` // 注册时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInfo) Reset() {
	*x = PlayerInfo{}
	mi := &file_push_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfo) ProtoMessage() {}

func (x *PlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_push_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfo.ProtoReflect.Descriptor instead.
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return file_push_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerInfo) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PlayerInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *PlayerInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *PlayerInfo) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *PlayerInfo) GetRegisterTime() string {
	if x != nil {
		return x.RegisterTime
	}
	return ""
}

// 房间简要信息
type RoomInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`              // 房间ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                // 展示名称
	MaxPlayers    int32                  `protobuf:"varint,3,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"` // 人数上限
	CurPlayers    int32                  `protobuf:"varint,4,opt,name=cur_players,json=curPlayers,proto3" json:"cur_players,omitempty"` // 当前人数
	OwnerUid      int64                  `protobuf:"varint,5,opt,name=owner_uid,json=ownerUid,proto3" json:"owner_uid,omitempty"`       // 房主用户ID
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`                           // 房间状态（如等待、游戏中，具体取值由业务约定）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomInfo) Reset() {
	*x = RoomInfo{}
	mi := &file_push_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInfo) ProtoMessage() {}

func (x *RoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_push_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInfo.ProtoReflect.Descriptor instead.
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return file_push_proto_rawDescGZIP(), []int{2}
}

func (x *RoomInfo) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoomInfo) GetMaxPlayers() int32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *RoomInfo) GetCurPlayers() int32 {
	if x != nil {
		return x.CurPlayers
	}
	return 0
}

func (x *RoomInfo) GetOwnerUid() int64 {
	if x != nil {
		return x.OwnerUid
	}
	return 0
}

func (x *RoomInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 房间内成员与座位
type RoomMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Seat          int32                  `protobuf:"varint,3,opt,name=seat,proto3" json:"seat,omitempty"`                      // 座位号
	IsReady       bool                   `protobuf:"varint,4,opt,name=is_ready,json=isReady,proto3" json:"is_ready,omitempty"` // 是否已准备
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomMember) Reset() {
	*x = RoomMember{}
	mi := &file_push_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomMember) ProtoMessage() {}

func (x *RoomMember) ProtoReflect() protoreflect.Message {
	mi := &file_push_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomMember.ProtoReflect.Descriptor instead.
func (*RoomMember) Descriptor() ([]byte, []int) {
	return file_push_proto_rawDescGZIP(), []int{3}
}

func (x *RoomMember) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *RoomMember) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *RoomMember) GetSeat() int32 {
	if x != nil {
		return x.Seat
	}
	return 0
}

func (x *RoomMember) GetIsReady() bool {
	if x != nil {
		return x.IsReady
	}
	return false
}

type CreateRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomInfo      *RoomInfo              `protobuf:"bytes,1,opt,name=room_info,json=roomInfo,proto3" json:"room_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomResponse) Reset() {
	*x = CreateRoomResponse{}
	mi := &file_push_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomResponse) ProtoMessage() {}

func (x *CreateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_push_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomResponse.ProtoReflect.Descriptor instead.
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return file_push_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRoomResponse) GetRoomInfo() *RoomInfo {
	if x != nil {
		return x.RoomInfo
	}
	return nil
}

type JoinRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomInfo      *RoomInfo              `protobuf:"bytes,1,opt,name=room_info,json=roomInfo,proto3" json:"room_info,omitempty"`
	Members       []*RoomMember          `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	SelfSeat      int32                  `protobuf:"varint,3,opt,name=self_seat,json=selfSeat,proto3" json:"self_seat,omitempty"` // 当前用户座位号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomResponse) Reset() {
	*x = JoinRoomResponse{}
	mi := &file_push_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomResponse) ProtoMessage() {}

func (x *JoinRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_push_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomResponse.ProtoReflect.Descriptor instead.
func (*JoinRoomResponse) Descriptor() ([]byte, []int) {
	return file_push_proto_rawDescGZIP(), []int{5}
}

func (x *JoinRoomResponse) GetRoomInfo() *RoomInfo {
	if x != nil {
		return x.RoomInfo
	}
	return nil
}

func (x *JoinRoomResponse) GetMembers() []*RoomMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *JoinRoomResponse) GetSelfSeat() int32 {
	if x != nil {
		return x.SelfSeat
	}
	return 0
}

type ExitRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExitRoomResponse) Reset() {
	*x = ExitRoomResponse{}
	mi := &file_push_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExitRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitRoomResponse) ProtoMessage() {}

func (x *ExitRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_push_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitRoomResponse.ProtoReflect.Descriptor instead.
func (*ExitRoomResponse) Descriptor() ([]byte, []int) {
	return file_push_proto_rawDescGZIP(), []int{6}
}

func (x *ExitRoomResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type RoomReadyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomInfo      *RoomInfo              `protobuf:"bytes,1,opt,name=room_info,json=roomInfo,proto3" json:"room_info,omitempty"`
	Members       []*RoomMember          `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	AllReady      bool                   `protobuf:"varint,3,opt,name=all_ready,json=allReady,proto3" json:"all_ready,omitempty"` // 是否全员已准备（业务可按需使用）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomReadyResponse) Reset() {
	*x = RoomReadyResponse{}
	mi := &file_push_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomReadyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomReadyResponse) ProtoMessage() {}

func (x *RoomReadyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_push_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomReadyResponse.ProtoReflect.Descriptor instead.
func (*RoomReadyResponse) Descriptor() ([]byte, []int) {
	return file_push_proto_rawDescGZIP(), []int{7}
}

func (x *RoomReadyResponse) GetRoomInfo() *RoomInfo {
	if x != nil {
		return x.RoomInfo
	}
	return nil
}

func (x *RoomReadyResponse) GetMembers() []*RoomMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *RoomReadyResponse) GetAllReady() bool {
	if x != nil {
		return x.AllReady
	}
	return false
}

var File_push_proto protoreflect.FileDescriptor

const file_push_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"push.proto\x12\x02pb\"D\n" +
	"\x11LoginGameResponse\x12/\n" +
	"\vplayer_info\x18\x01 \x01(\v2\x0e.pb.PlayerInfoR\n" +
	"playerInfo\"\x89\x01\n" +
	"\n" +
	"PlayerInfo\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x10\n" +
	"\x03sex\x18\x04 \x01(\x05R\x03sex\x12#\n" +
	"\rregister_time\x18\x05 \x01(\tR\fregisterTime\"\xae\x01\n" +
	"\bRoomInfo\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vmax_players\x18\x03 \x01(\x05R\n" +
	"maxPlayers\x12\x1f\n" +
	"\vcur_players\x18\x04 \x01(\x05R\n" +
	"curPlayers\x12\x1b\n" +
	"\towner_uid\x18\x05 \x01(\x03R\bownerUid\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\"i\n" +
	"\n" +
	"RoomMember\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x12\n" +
	"\x04seat\x18\x03 \x01(\x05R\x04seat\x12\x19\n" +
	"\bis_ready\x18\x04 \x01(\bR\aisReady\"?\n" +
	"\x12CreateRoomResponse\x12)\n" +
	"\troom_info\x18\x01 \x01(\v2\f.pb.RoomInfoR\broomInfo\"\x84\x01\n" +
	"\x10JoinRoomResponse\x12)\n" +
	"\troom_info\x18\x01 \x01(\v2\f.pb.RoomInfoR\broomInfo\x12(\n" +
	"\amembers\x18\x02 \x03(\v2\x0e.pb.RoomMemberR\amembers\x12\x1b\n" +
	"\tself_seat\x18\x03 \x01(\x05R\bselfSeat\"+\n" +
	"\x10ExitRoomResponse\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"\x85\x01\n" +
	"\x11RoomReadyResponse\x12)\n" +
	"\troom_info\x18\x01 \x01(\v2\f.pb.RoomInfoR\broomInfo\x12(\n" +
	"\amembers\x18\x02 \x03(\v2\x0e.pb.RoomMemberR\amembers\x12\x1b\n" +
	"\tall_ready\x18\x03 \x01(\bR\ballReadyB\x06Z\x04./pbb\x06proto3"

var (
	file_push_proto_rawDescOnce sync.Once
	file_push_proto_rawDescData []byte
)

func file_push_proto_rawDescGZIP() []byte {
	file_push_proto_rawDescOnce.Do(func() {
		file_push_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_push_proto_rawDesc), len(file_push_proto_rawDesc)))
	})
	return file_push_proto_rawDescData
}

var file_push_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_push_proto_goTypes = []any{
	(*LoginGameResponse)(nil),  // 0: pb.LoginGameResponse
	(*PlayerInfo)(nil),         // 1: pb.PlayerInfo
	(*RoomInfo)(nil),           // 2: pb.RoomInfo
	(*RoomMember)(nil),         // 3: pb.RoomMember
	(*CreateRoomResponse)(nil), // 4: pb.CreateRoomResponse
	(*JoinRoomResponse)(nil),   // 5: pb.JoinRoomResponse
	(*ExitRoomResponse)(nil),   // 6: pb.ExitRoomResponse
	(*RoomReadyResponse)(nil),  // 7: pb.RoomReadyResponse
}
var file_push_proto_depIdxs = []int32{
	1, // 0: pb.LoginGameResponse.player_info:type_name -> pb.PlayerInfo
	2, // 1: pb.CreateRoomResponse.room_info:type_name -> pb.RoomInfo
	2, // 2: pb.JoinRoomResponse.room_info:type_name -> pb.RoomInfo
	3, // 3: pb.JoinRoomResponse.members:type_name -> pb.RoomMember
	2, // 4: pb.RoomReadyResponse.room_info:type_name -> pb.RoomInfo
	3, // 5: pb.RoomReadyResponse.members:type_name -> pb.RoomMember
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_push_proto_init() }
func file_push_proto_init() {
	if File_push_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_push_proto_rawDesc), len(file_push_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_push_proto_goTypes,
		DependencyIndexes: file_push_proto_depIdxs,
		MessageInfos:      file_push_proto_msgTypes,
	}.Build()
	File_push_proto = out.File
	file_push_proto_goTypes = nil
	file_push_proto_depIdxs = nil
}
